name: themilliondollarbrand
favicon: null
layout_spectrum: 0.16641323873773217
typography_spectrum: 0.8974422805476934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7924646225292236
  lightness: 0.6881745709106326
  saturation: 0.17669988563284278
  rhythmicContrast: 0.972105128923431
purpose: []
